### ISSUE TITLE
Incompatible with bytes 1.

### ISSUE THREAD

**Issue by gklijs** [Rantanen/protofish#1]
Hi, I use this library for working with schema registry, and currently the build fails when updating dependencies, because of the bytes dependency.
The error can be found here: https://github.com/gklijs/schema_registry_converter/pull/43.

Could you please update the bytes dependency to "^1.0" and cut a new release?

**Comment by Rantanen** [comment]
Done in  8ba567950c901bc37e228a650e22de9e826099f4 ! Should be available as 0.3.0 on crates.io.

Most of the testing I've put protofish through has been through Proxide so while protofish tests didn't catch any failures, I'm not entirely sure how comprehensive they are. In case there are issues, do get back to me!

**Comment by gklijs** [comment]
Seems fine, at least it did not break the test. Thanks a lot.
