### ISSUE TITLE
Support for encoding messages?

### ISSUE THREAD

**Issue by hudsonft** [Rantanen/protofish#3]
Thanks so much for making this crate! Really valuable to enable generalized tools (loggers, etc) with a library like this.

Wondering if there are any plans to support encoding messages as well with protofish? Would be super useful for my application.

Thanks again for this work!

**Comment by Rantanen** [comment]
Uh..

The last I was working on Proxide, I was integrating a scripting engine for the purpose of transforming gRPC messages on the fly.

... fully remembering Protofish was able to do encoding already.

Guess that's not the case! I _was_ looking for something relatively simple and straight forward to implement anyway, guess I've got that now! :)

**Comment by hudsonft** [comment]
great, thank you! Do you have a sense for when you'd plan to work on this? Not trying to push for any time specifically (really appreciate you taking this on) just looking for a general idea (like, a few days? weeks? months?) for my own planning.

Thanks again for the great support for this OSS

**Comment by Rantanen** [comment]
An hour? Apparently I had implemented encoding for the above purpose already, but never got it committed to the repository... >_>

Currently checking for clippy lints, etc.

There have been _some_ changes to the API I think, but I've got no memory what they are. Just saw a commit message that indicated that was the case. Will get more details when I actually figure out what I've done half a year ago!

**Comment by Rantanen** [comment]
Also I just realized I never set up proper CI for protofish on its own. It's been somewhat tightly coupled to Proxide in that sense.

I've pushed the changes to github, but I'd like to cover them with more unit tests and to set up proper CI over Github actions.

Would you be okay pulling the dependency directly off Github for a while or would you prefer crates.io pre-release? I think crates.io supports those as far as I remember. Cargo supports github dependencies at least with:

```toml
protofish = { git = "https://github.com/Rantanen/protofish" }
```

**Comment by Rantanen** [comment]
Also from what I could tell by reviewing the changes, the version incompatible changes were mainly changes to default exports (instead of re-exporting stuff in the crate root, there's now a prelude mod that has the most common bits) and error types (at least some internal fns changed from Result<S, Error> to Result<S, ParseError>.

All other changes (as far as I could tell from a quick review) were internal function signatures, etc.

**Comment by Rantanen** [comment]
... and most importantly (Have fun with any possible notifications! ^^)

The encode is on the `Message` (since docs.rs won't be updating until I push a version to crates.io).

```rust
    let msg = context.get_message("Message").unwrap();

    let value = msg.decode(&original, &context);
    let encoded = value.encode(&context);

    assert_eq!(original, encoded);
```

**Comment by Rantanen** [comment]
Just release 0.4.0 on Crates.io.

There was still a problem in encoding that affected sub-messages. The top level protobuf message does not have the content length embedded in the binary as it's expected to be communicated on the top level protocol (such as `Content-Length` header, etc.). The embedded messages, being variable length fields, should have that length though, but it was missing, which resulted in corrupted encode output. That should be fixed now as well.

The tests aren't comprehensive in any way and do not rely on any external reference data - but at least encode and decode itself seem to be somewhat consistent with each other with roundtrip tests succeeding. Decode has been tested through Proxide in the past so it _seems_ to work with real life data.

**Comment by hudsonft** [comment]
Ah sorry I missed these, thanks for the info and support. I will try this out, excited to use
